version: '3.8'

services:
  app:
    image: node:18
    container_name: nodejs-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:k7119zamu@db:5432/urlshortener
    depends_on:
      - db
    command: >
      sh -c "npm install && npm run start"
      
  db:
    image: postgres:17
    container_name: postgres-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=k7119zamu
      - POSTGRES_DB=urlshortener
    ports:
      - '5433:5432'

volumes:
  pgdata:
